apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-claim
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
